### ISSUE TITLE
`(FunctionClauseError) no function clause matching in Electric.Postgres.Extension.SchemaCache.name/1`

### ISSUE THREAD

**Issue by kimjisena** [electric-sql/electric#1308]
I'm trying `electric-sql` for the first time. Everything seems to be working ok except when I run migrations through the proxy I get this error:

```
$ bun src/db/migrate.ts
127 |     })
128 | 
129 |     this._attachListeners(con)
130 | 
131 |     con.once('end', () => {
132 |       const error = this._ending ? new Error('Connection terminated') : new Error('Connection terminated unexpectedly')
                                                                              ^
error: Connection terminated unexpectedly
      at /Volumes/Kos/Projects/api/node_modules/pg/lib/client.js:132:73
      at node:events:33:51
      at emit (node:events:161:95)
      at /Volumes/Kos/Projects/api/node_modules/pg/lib/connection.js:63:7
      at node:net:12:43

Bun v1.1.10 (macOS arm64)
error: script "migrate" exited with code 1
```

Here's what the container logs look like.

```
07:19:21.445 pid=<0.3059.0> [info] Starting ElectricSQL 0.11.1 in logical_replication mode.
07:19:21.451 pid=<0.3060.0> [info] Running Electric.Plug.Router with Bandit 1.1.3 at :::5133 (http)
07:19:26.129 pid=<0.3052.0> [info] tzdata release in place is from a file last modified Fri, 22 Oct 2021 02:20:47 GMT. Release file on server was last modified Thu, 01 Feb 2024 18:40:48 GMT.
07:19:27.847 pid=<0.3047.0> [info] Tzdata has updated the release from 2021e to 2024a
07:19:32.370 pid=<0.3695.0> pg_client=::ffff:192.168.65.1:54256 [error] GenServer #PID<0.3695.0> terminating
** (FunctionClauseError) no function clause matching in Electric.Postgres.Extension.SchemaCache.name/1
    (electric 0.11.1) lib/electric/postgres/extension/schema_cache.ex:56: Electric.Postgres.Extension.SchemaCache.name(nil)
    (electric 0.11.1) lib/electric/postgres/extension/schema_cache.ex:67: Electric.Postgres.Extension.SchemaCache.ready?/1
    (electric 0.11.1) lib/electric/replication/postgres/tcp_server.ex:235: Electric.Replication.Postgres.TcpServer.initialize_connection/3
    (electric 0.11.1) deps/thousand_island/lib/thousand_island/handler.ex:411: Electric.Replication.Postgres.TcpServer.handle_continue/2
    (stdlib 4.3.1.3) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3.1.3) gen_server.erl:865: :gen_server.loop/7
    (stdlib 4.3.1.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:continue, :handle_connection}
```

I'm using `drizzle-orm` for my data models and `migrate.ts` looks like this:

```ts
// src/db/migrate.ts
import "dotenv/config";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { db, proxy } from "./proxy";
import { sql } from "drizzle-orm";
 
// This will run migrations on the database, skipping the ones already applied
await migrate(db, {
  migrationsFolder: "./src/db/migrations",
  migrationsTable: "__ladha_migrations",
  migrationsSchema: "ladha",
});
 
// electrify tables
await db.execute(sql`ALTER TABLE users ENABLE ELECTRIC;`);
 
// close the connection, otherwise the script will hang
await proxy.end();
```

**Comment by alco** [comment]
Hey @kimjisena :wave: 

Please share your server config (with sensitive info redacted). The error you get looks quite unusual, I'd like to try reproducing it.

**Comment by kimjisena** [comment]
Hi @alco 

What server configs are you referring to?

I basically have this `esql-up.sh` script (the docker command from the docs):

```sh
#!/bin/bash
set -e

docker run \
    -e "DATABASE_REQUIRE_SSL=false" \
    -e 'DATABASE_URL=postgres://postgres:user@postgres:5432/db_name' \
    -e "LOGICAL_PUBLISHER_HOST=localhost" \
    -e "PG_PROXY_PASSWORD=<password>" \
    -e "AUTH_MODE=insecure" \
    -p 5133:5133 \
    -p 5433:5433 \
    -p 65432:65432 \
    -t \
    electricsql/electric
```

Here's my drizzle config:

```ts
import "dotenv/config";
import { defineConfig } from "drizzle-kit";

export default defineConfig({
  schema: "./src/db/schemas/index.ts",
  out: "./src/db/migrations",
  dialect: "postgresql",
  //! use this for running migrations
  dbCredentials: {
    host: process.env.ELECTRIC_PG_HOST as string,
    port: Number(process.env.ELECTRIC_PG_PORT),
    user: process.env.ELECTRIC_PG_USER,
    password: process.env.ELECTRIC_PG_PASSWORD,
    database: process.env.ELECTRIC_PG_NAME as string,
    ssl: false,
  },

  //! use this for drizzle studio and any other database access
  // dbCredentials: {
  //   host: process.env.PG_HOST as string,
  //   port: Number(process.env.PG_PORT),
  //   user: process.env.PG_USER,
  //   password: process.env.PG_PASSWORD,
  //   database: process.env.PG_NAME as string,
  //   ssl: false,
  // },
  verbose: true,
  strict: true,
});
```

Not sure if there's other config that I have missed as per the docs.

**Comment by alco** [comment]
@kimjisena Try replacing the `LOGICAL_PUBLISHER_HOST=localhost` variable with `ELECTRIC_WRITE_TO_PG_MODE=direct_writes`.

**Comment by kimjisena** [comment]
That fixes the `electric-sql` error but I'm still getting this when I run migrations

```sh
$ bun src/db/migrate.ts
127 |     })
128 | 
129 |     this._attachListeners(con)
130 | 
131 |     con.once('end', () => {
132 |       const error = this._ending ? new Error('Connection terminated') : new Error('Connection terminated unexpectedly')
                                                                              ^
error: Connection terminated unexpectedly
      at /Volumes/Kos/Projects/api/node_modules/pg/lib/client.js:132:73
      at node:events:33:51
      at emit (node:events:161:95)
      at /Volumes/Kos/Projects/api/node_modules/pg/lib/connection.js:63:7
      at node:net:12:43

Bun v1.1.10 (macOS arm64)
error: script "migrate" exited with code 1
```

The `electric-sql` logs:
```
09:34:43.980 pid=<0.3059.0> [info] Starting ElectricSQL 0.11.1 in direct_writes mode.
09:34:43.984 pid=<0.3060.0> [info] Running Electric.Plug.Router with Bandit 1.1.3 at :::5133 (http)
09:34:48.466 pid=<0.3052.0> [info] tzdata release in place is from a file last modified Fri, 22 Oct 2021 02:20:47 GMT. Release file on server was last modified Thu, 01 Feb 2024 18:40:48 GMT.
09:34:50.103 pid=<0.3047.0> [info] Tzdata has updated the release from 2021e to 2024a
```

**Comment by alco** [comment]
@kimjisena It is concerning that you're not seeing any errors in the Docker container log.

Are you using the same password for the database and the migrations proxy? If not, can you double-check that you configure drizzle with the proxy password?

We had one code path that could result in Electric not logging any errors when it failed to connect to the database. That issue has been fixed in `main`, pending a new release. In the meantime, you could try running the canary image of Electric (`electricsq/electric:canary`) to see if that causes an error to be logged for your use case,

**Comment by kimjisena** [comment]
I'm using different passwords for the db (prefix `PG_`) and the migrations proxy(prefix `ELECTRIC_PG_`). Drizzle is configured to run with the migrations proxy as seen below:

```
import { drizzle } from "drizzle-orm/node-postgres";
import { Client } from "pg";
import * as schema from "./schemas";

export const proxy = new Client({
  connectionString: `postgres://${process.env.ELECTRIC_PG_USER}:${process.env.ELECTRIC_PG_PASSWORD}@${process.env.ELECTRIC_PG_HOST}:${process.env.ELECTRIC_PG_PORT}/${process.env.ELECTRIC_PG_NAME}?replication=logical&sslmode=disable`,
});

await proxy.connect();
export const db = drizzle(proxy, { schema });
```

Let me try the canary image.

**Comment by alco** [comment]
Hi @kimjisena . Any luck getting it to work?

**Comment by KyleAMathews** [comment]
👋 we've been working the last month on a rebuild of the Electric server over at a temporary repo https://github.com/electric-sql/electric-next/

You can read more about why we made the decision at https://next.electric-sql.com/about

We're really excited about all the new possibilities the new server brings and we hope you'll check it out soon and give us your feedback.

We're now moving the temporary repo back here. As part of that migration we're closing all the old issues and PRs. We really appreciate you taking the time to investigate and report this issue!
