### ISSUE TITLE
electric-sql generate fails in pnpm monorepo

### ISSUE THREAD

**Issue by emckay** [electric-sql/electric#1425]
Perhaps related to #741

`electric-sql generate` fails in my project using pnpm's workspace features.

here's a minimal reproduction with the `create-electric-app` being set up in a pnpm workspace: https://github.com/emckay/electricsql-workspace-bug-repro

To run it locally:
```
git clone https://github.com/emckay/electricsql-workspace-bug-repro
cd electricsql-workspace-bug-repro
pnpm install
cd packages/electric-test
pnpm backend:start
```

in another terminal
```
pnpm db:migrate
pnpm client:generate
```

This produces this error:

```
pnpm client:generate

> electric-test@0.1.0 client:generate /Users/eric/tmp/electricsql-workspace-bug-repro/packages/electric-test
> electric-sql generate

Generating Electric client...
Service URL: http://localhost:5133
Proxy URL: postgresql://postgres:********@localhost:65432/electric-test?sslmode=disable
Error: Command failed: node /Users/eric/tmp/electricsql-workspace-bug-repro/node_modules/.pnpm/prisma@4.16.2/node_modules/prisma/build/index.js db pull --schema=".electric_migrations_tmp_Hh30GSASvbm1/prisma/schema.prisma"
Error: P1017

Server has closed the connection.


    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:530:35)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'node /Users/eric/tmp/electricsql-workspace-bug-repro/node_modules/.pnpm/prisma@4.16.2/node_modules/prisma/build/index.js db pull --schema=".electric_migrations_tmp_Hh30GSASvbm1/prisma/schema.prisma"'
}
generate command failed: Introspection script exited with error code: 1
 ELIFECYCLE  Command failed with exit code 1.
 
```
 
 and these logs in the electric service/postgres docker:

```
electric-test-electric-1  | 16:34:34.905 pid=<0.4027.0> proxy_session_id=3 [info] Matched prisma introspection query to Elixir.Electric.Postgres.Proxy.Prisma.Query.NamespaceVersionV5_2
electric-test-electric-1  | 16:34:34.910 pid=<0.4027.0> proxy_session_id=3 [info] Matched prisma introspection query to Elixir.Electric.Postgres.Proxy.Prisma.Query.NamespaceV5_2
electric-test-electric-1  | 16:34:34.916 pid=<0.4027.0> proxy_session_id=3 [info] Matched prisma introspection query to Elixir.Electric.Postgres.Proxy.Prisma.Query.TableV5_2
electric-test-electric-1  | 16:34:34.920 pid=<0.4027.0> proxy_session_id=3 [info] Matched prisma introspection query to Elixir.Electric.Postgres.Proxy.Prisma.Query.ConstraintV5_2
electric-test-electric-1  | 16:34:34.923 pid=<0.4027.0> proxy_session_id=3 [info] Matched prisma introspection query to Elixir.Electric.Postgres.Proxy.Prisma.Query.ViewV5_2
electric-test-electric-1  | 16:34:34.927 pid=<0.4027.0> proxy_session_id=3 [error] Received unknown prisma introspection query: "\n            SELECT t.typname as name, e.enumlabel as value, n.nspname as namespace, d.description\n            FROM pg_type t\n            JOIN pg_enum e ON t.oid = e.enumtypid\n            JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace\n            LEFT OUTER JOIN pg_description d ON d.objoid = t.oid\n            WHERE n.nspname = ANY ( $1 )\n            ORDER BY e.enumsortorder" with columns ["name", "value", "namespace", "d.description"]
electric-test-electric-1  | 16:34:34.928 pid=<0.4027.0> proxy_session_id=3 [error] GenServer #PID<0.4027.0> terminating
electric-test-electric-1  | ** (MatchError) no match of right hand side value: :error
electric-test-electric-1  |     (elixir 1.17.0) lib/enum.ex:1829: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
electric-test-electric-1  |     (elixir 1.17.0) lib/enum.ex:1829: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
electric-test-electric-1  |     (electric 0.12.1) lib/electric/postgres/proxy/injector/prisma.ex:35: Electric.Postgres.Proxy.Injector.Operation.Electric.Postgres.Proxy.Injector.Prisma.recv_client/3
electric-test-electric-1  |     (electric 0.12.1) lib/electric/postgres/proxy/injector/operation.ex:286: Electric.Postgres.Proxy.Injector.Operation.List.recv_client/3
electric-test-electric-1  |     (electric 0.12.1) lib/electric/postgres/proxy/injector.ex:125: Electric.Postgres.Proxy.Injector.recv_client/2
electric-test-electric-1  |     (electric 0.12.1) lib/electric/postgres/proxy/handler.ex:207: Electric.Postgres.Proxy.Handler.handle_messages/3
electric-test-electric-1  |     (electric 0.12.1) deps/thousand_island/lib/thousand_island/handler.ex:379: Electric.Postgres.Proxy.Handler.handle_info/2
electric-test-electric-1  |     (stdlib 6.0) gen_server.erl:2173: :gen_server.try_handle_info/3
electric-test-electric-1  | Last message: {:tcp, #Port<0.33>, <<67, 0, 0, 0, 8, 83, 115, 53, 0, 83, 0, 0, 0, 4, 80, 0, 0, 1, 141, 115, 54, 0, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 83, 69, 76, 69, 67, 84, 32, 116, 46, 116, 121, 112, ...>>}
electric-test-electric-1  | 16:34:35.472 pid=<0.2904.0> [notice]     :alarm_handler: {:set, {:system_memory_high_watermark, []}}
```

**Comment by alco** [comment]
@emckay Hi. This is likely caused by the Prisma version you have installed. Can you try it with Prisma version 4.8.1?

**Comment by emckay** [comment]
Got it. Pinning the version of prisma to 4.8.1 fixed the issue. Thank you!
