### ISSUE TITLE
Cannot convert null to bigint (and presumably other types)

### ISSUE THREAD

**Issue by KyleAMathews** [electric-sql/electric#1507]
The parser tries to convert a null to bigint. We probably need to load into the schema if a column can be null or not (it'd be useful for creating types e.g. Typescript types.

```
TypeError: Cannot convert null to a BigInt
    at BigInt (<anonymous>)
    at parseBigInt (parser.ts:11:40)
    at MessageParser.parseRow (parser.ts:128:12)
    at parser.ts:95:27
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (parser.ts:94:26)
    at JSON.parse (<anonymous>)
    at MessageParser.parse (parser.ts:87:17)
    at ShapeStream.<anonymous> (client.ts:267:40)
    at Generator.next (<anonymous>)
```

**Comment by KyleAMathews** [comment]
Fixed by #1509
