### ISSUE TITLE
Telemtry Error: Electric.Telemetry.CallHomeReporter terminating

### ISSUE THREAD

**Issue by Makisuo** [electric-sql/electric#2200]
This doesnt crash the server. 
Happens around every 30 sec.

**Operating System**
Ubuntu 24.04.1 LTS ARM

Docker version 27.4.1, build b9d17ea
electricsql/electric:1.0.0-beta.2

```shell
00:08:33.231 pid=<0.2609.0> [error] GenServer Electric.Telemetry.CallHomeReporter terminating
** (stop) :terminating
    (finch 0.19.0) lib/finch/http1/pool.ex:96: Finch.HTTP1.Pool.request/6
    (finch 0.19.0) lib/finch.ex:493: anonymous fn/4 in Finch.request/3
    (telemetry 1.2.1) /app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (req 0.5.7) lib/req/finch.ex:239: Req.Finch.run_finch_request/3
    (req 0.5.7) lib/req/finch.ex:71: Req.Finch.run/4
    (req 0.5.7) lib/req/request.ex:1103: Req.Request.run_request/1
    (req 0.5.7) lib/req/request.ex:1047: Req.Request.run/1
    (req 0.5.7) lib/req.ex:1100: Req.request!/2
    (electric 1.0.0-beta.2) lib/electric/telemetry/call_home_reporter.ex:31: Electric.Telemetry.CallHomeReporter.report_home/1
    (stdlib 6.0.1) gen_server.erl:2221: :gen_server.try_terminate/3
    (stdlib 6.0.1) gen_server.erl:2422: :gen_server.terminate/10
    (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
Process Label: {:call_home_reporter, Electric.Telemetry.CallHomeReporter}
Last message: {:EXIT, #PID<0.2606.0>, :shutdown}

00:08:33.253 pid=<0.2420.0> [notice]     :alarm_handler: {:clear, :system_memory_high_watermark}

---
00:08:31.852 pid=<0.2608.0> [error] Error when calling MFA defined by measurement: Electric.Telemetry :get_system_memory_usage [
  [
    stack_id: "single_stack",
    storage: {Electric.ShapeCache.FileStorage,
     [storage_dir: "./persistent/shapes"]}
  ]
]
Class=:error
Reason=:badarith
Stacktrace=[
  {Electric.Telemetry, :get_system_memory_usage, 1,
   [file: ~c"lib/electric/telemetry.ex", line: 329]},
  {:telemetry_poller, :make_measurement, 1,
   [file: ~c"/app/deps/telemetry_poller/src/telemetry_poller.erl", line: 336]},
  {:telemetry_poller, :"-make_measurements_and_filter_misbehaving/1-lc$^0/1-0-",
   1,
   [file: ~c"/app/deps/telemetry_poller/src/telemetry_poller.erl", line: 332]},
  {:telemetry_poller, :"-make_measurements_and_filter_misbehaving/1-lc$^0/1-0-",
   1,
   [file: ~c"/app/deps/telemetry_poller/src/telemetry_poller.erl", line: 332]},
  {:telemetry_poller, :handle_info, 2,
   [file: ~c"/app/deps/telemetry_poller/src/telemetry_poller.erl", line: 354]},
  {:gen_server, :try_handle_info, 3, [file: ~c"gen_server.erl", line: 2173]},
  {:gen_server, :handle_msg, 6, [file: ~c"gen_server.erl", line: 2261]},
  {:proc_lib, :init_p_do_apply, 3, [file: ~c"proc_lib.erl", line: 329]}
]
```

**Comment by alco** [comment]
@Makisuo Thanks for the report! We'll look into it.
