### ISSUE TITLE
Crash when writing to a table

### ISSUE THREAD

**Issue by ccapndave** [electric-sql/electric#495]
I create my schema, then write a row using:

```

```
17:19:25.206 pid=<0.2812.0> origin=postgres_1 [info] connect: %{host: ~c"database", ssl: false, timeout: 5000, username: ~c"postgres"}
2023-09-25 17:19:25.289 UTC [39] ERROR:  subscription "postgres_1" already exists
2023-09-25 17:19:25.289 UTC [39] STATEMENT:  CREATE SUBSCRIPTION "postgres_1" CONNECTION 'host=electric port=5433 dbname=electric connect_timeout=5000' PUBLICATION "electric_publication" WITH (connect = false)
17:19:25.296 pid=<0.2812.0> origin=postgres_1 [info] Successfully initialized origin postgres_1 at extension version
17:19:25.296 pid=<0.2825.0> pg_producer=postgres_1 [info] Starting Elixir.Electric.Postgres.Extension.SchemaCache for postgres_1
17:19:25.296 pid=<0.2825.0> pg_producer=postgres_1 [warning] SchemaCache "postgres_1" registered as the global instance
2023-09-25 17:19:25.313 UTC [42] ERROR:  replication slot "electric_replication_out_test" already exists
2023-09-25 17:19:25.313 UTC [42] STATEMENT:  CREATE_REPLICATION_SLOT "electric_replication_out_test" LOGICAL pgoutput NOEXPORT_SNAPSHOT
17:19:25.316 pid=<0.2825.0> pg_producer=postgres_1 [info] CREATE TABLE acknowledged_client_lsns (...)
17:19:25.349 pid=<0.2818.0> client_id=e702374f-ca6f-4a41-b9d2-505a5bf184c9 instance_id=4d01a55a-6b4a-4500-a362-b6522b58855f user_id=dummy [error] GenServer #PID<0.2818.0> terminating
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: the table identifier does not refer to an existing ETS table

    (stdlib 4.3.1.2) :ets.last(:ets_backed_cached_wal)
    (electric 0.6.3) lib/electric/postgres/cached_wal/ets_backed.ex:66: Electric.Postgres.CachedWal.EtsBacked.get_current_position/0
    (electric 0.6.3) lib/electric/satellite/ws_server.ex:172: Electric.Satellite.WebsocketServer.handle_info/2
    (bandit 1.0.0-pre.14) lib/bandit/websocket/connection.ex:187: Bandit.WebSocket.Connection.handle_info/3
    (bandit 1.0.0-pre.14) /app/deps/thousand_island/lib/thousand_island/handler.ex:94: Bandit.WebSocket.Handler.handle_info/2
    (stdlib 4.3.1.2) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3.1.2) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.3.1.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:perform_initial_sync_and_subscribe, %Electric.Satellite.SatInStartReplicationReq{lsn: "", options: [], subscription_ids: [], schema_version: "20230925125227_910"}}
```

**Comment by kevin-dp** [comment]
Hi @ccapndave, would you mind sharing your schema such that we can reproduce the problem and investigate further.

**Comment by ccapndave** [comment]
Sure!

```
/* Notes */

CREATE TABLE note (
	id uuid NOT NULL PRIMARY KEY,

	html text NOT NULL,

	inserted_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

/* Nodes */

CREATE TABLE link_node (
	id uuid NOT NULL PRIMARY KEY,

	note_id uuid NOT NULL REFERENCES note(id)
);

CREATE TABLE contact_node (
	id uuid NOT NULL PRIMARY KEY,	

	contact_id text NOT NULL,
	given_name text,
	family_name text
);

CREATE TABLE node (
	id uuid NOT NULL PRIMARY KEY,	
 
	/* Only one of these can be NOT NULL at a time; we can ensure this with a CHECK CONSTRAINT in the future */
	link_node_id uuid REFERENCES link_node(id),
	contact_node_id uuid REFERENCES contact_node(id)
);

/* Edges */

CREATE TABLE edge (
	id uuid NOT NULL PRIMARY KEY,

	confidence double precision NOT NULL,

	from_node uuid NOT NULL REFERENCES node(id),
	to_node uuid NOT NULL REFERENCES node(id)
);

/* This has to be added after table creation otherwise we have a circular reference */

ALTER TABLE link_node ADD COLUMN validated_edge_id uuid REFERENCES edge(id);

/* ⚡ Electrify ⚡ */

CALL electric.electrify('link_node');
CALL electric.electrify('contact_node');
CALL electric.electrify('node');
CALL electric.electrify('edge');
CALL electric.electrify('note');

-- ALTER TABLE link_node ENABLE ELECTRIC;
-- ALTER TABLE contact_node ENABLE ELECTRIC;
-- ALTER TABLE node ENABLE ELECTRIC;
-- ALTER TABLE edge ENABLE ELECTRIC;
-- ALTER TABLE note ENABLE ELECTRIC;
```

**Comment by kevin-dp** [comment]
I managed to reproduce your issue.
The problem comes from the timestamps you are saving into the SQLite database.
You are storing them as ISO strings but Electric expects timestamps without time zones to be stored as an ISO string but without the T and the Z.
i.e. you're writing timestamps like: `2023-08-23T09:10:11.001Z` but Electric expects `2023-08-23 09:10:11.001`.

This should work:

```ts
const note = await db.note.create({
  data: {
    id: noteToWrite.id,
    html: noteToWrite.html,
    inserted_at: noteToWrite.insertedAt.toISOString().replace('T', ' ').replace('Z', ''),
    updated_at: noteToWrite.updatedAt.toISOString().replace('T', ' ').replace('Z', '')
  }
});
```

Can you confirm?

PS: This problem should be fixed soon because we are working on integrating timestamp support on the client so in the future you will be able to pass in a `Date` object and it will be formatted and stored correctly in SQLite for you.
