### ISSUE TITLE
Unable to replicate boolean columns

### ISSUE THREAD

**Issue by gorbak25** [electric-sql/electric#512]
For the following prisma schema:
```
model Column {
  id                String        @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  tableId           String        @map("table_id") @db.Uuid
  orderId           Float         @map("order_id")
  name              String
  type              Int
  integrationId     String?       @map("integration_id")
  autoRun           Boolean       @map("auto_run")
  integrationConfig String?       @map("integration_config")
  createdAt         Float         @map("created_at")
  electricUserId    String        @map("electric_user_id")
}
```
The generated client side schema expects a number not a boolean in the schema:
```
/////////////////////////////////////////
// COLUMN SCHEMA
/////////////////////////////////////////

export const ColumnSchema = z.object({
  id: z.string(),
  table_id: z.string(),
  order_id: z.number(),
  name: z.string(),
  type: z.number().int(),
  integration_id: z.string().nullable(),
  auto_run: z.number().int(),
  integration_config: z.string().nullable(),
  created_at: z.number(),
  electric_user_id: z.string(),
})

export type Column = z.infer<typeof ColumnSchema>
```
Which is problematic as the satelite protocol expects that boolean values are encoded as either "f" or "t". So it crashes when the client sends a number.
```
23:11:55.195 pid=<0.2829.0> client_id=32d8b3f7-8d6f-4d0d-a4e6-baa3b7520447 instance_id=0cac0837-170a-4e79-9ca4-be2c47ca9670 user_id=43c4785e-51a8-4805-b17b-b483ab69d83b [debug] ws data received: %Electric.Satellite.SatOpLog{ops: [%Electric.Satellite.SatTransOp{op: {:begin, %Electric.Satellite.SatOpBegin{commit_timestamp: 1696029114724, trans_id: "", lsn: <<0, 0, 0, 40>>, origin: nil, is_migration: false}}}, %Electric.Satellite.SatTransOp{op: {:update, %Electric.Satellite.SatOpUpdate{relation_id: 0, row_data: %Electric.Satellite.SatOpRow{nulls_bitmask: "p", values: ["17cf2b1a-a1c7-4776-8a74-ff56e663c3b7", "", "", ""]}, old_row_data: nil, tags: ["32d8b3f7-8d6f-4d0d-a4e6-baa3b7520447@1696029114684"]}}}, %Electric.Satellite.SatTransOp{op: {:insert, %Electric.Satellite.SatOpInsert{relation_id: 1, row_data: %Electric.Satellite.SatOpRow{nulls_bitmask: <<5, 0>>, values: ["ffef2a0c-3e70-4ec9-8970-f4765aedaa7a", "17cf2b1a-a1c7-4776-8a74-ff56e663c3b7", "0.1", "column_ffef2a0c-3e70-4ec9-8970-f4765aedaa7a", "0", "", "0", "", "1696029114685.1", "43c4785e-51a8-4805-b17b-b483ab69d83b"]}, tags: []}}}, %Electric.Satellite.SatTransOp{op: {:update, %Electric.Satellite.SatOpUpdate{relation_id: 0, row_data: %Electric.Satellite.SatOpRow{nulls_bitmask: "p", values: ["17cf2b1a-a1c7-4776-8a74-ff56e663c3b7", "", "", ""]}, old_row_data: nil, tags: []}}}, %Electric.Satellite.SatTransOp{op: {:insert, %Electric.Satellite.SatOpInsert{relation_id: 1, row_data: %Electric.Satellite.SatOpRow{nulls_bitmask: <<5, 0>>, values: ["2615e55d-21bc-4f2c-8520-55258d123c85", "17cf2b1a-a1c7-4776-8a74-ff56e663c3b7", "1.1", "column_2615e55d-21bc-4f2c-8520-55258d123c85", "0", "", "0", "", "1696029114685.1", "43c4785e-51a8-4805-b17b-b483ab69d83b"]}, tags: []}}}, %Electric.Satellite.SatTransOp{op: {:update, %Electric.Satellite.SatOpUpdate{relation_id: 0, row_data: %Electric.Satellite.SatOpRow{nulls_bitmask: "p", values: ["17cf2b1a-a1c7-4776-8a74-ff56e663c3b7", "", "", ""]}, old_row_data: nil, tags: []}}}, %Electric.Satellite.SatTransOp{op: {:insert, %Electric.Satellite.SatOpInsert{relation_id: 1, row_data: %Electric.Satellite.SatOpRow{nulls_bitmask: <<5, 0>>, values: ["f3bd4ddb-86a7-4f0e-afb0-5a3b6de9e421", "17cf2b1a-a1c7-4776-8a74-ff56e663c3b7", "2.1", "column_f3bd4ddb-86a7-4f0e-afb0-5a3b6de9e421", "0", "", "0", "", "1696029114685.1", "43c4785e-51a8-4805-b17b-b483ab69d83b"]}, tags: []}}}, %Electric.Satellite.SatTransOp{op: {:update, %Electric.Satellite.SatOpUpdate{relation_id: 0, row_data: %Electric.Satellite.SatOpRow{nulls_bitmask: "p", values: ["17cf2b1a-a1c7-4776-8a74-ff56e663c3b7", "", "", ""]}, old_row_data: nil, tags: []}}}, %Electric.Satellite.SatTransOp{op: {:insert, %Electric.Satellite.SatOpInsert{relation_id: 3, row_data: %Electric.Satellite.SatOpRow{nulls_bitmask: <<0>>, values: ["59e4b3e6-f932-426e-8157-49607fef93d2", "17cf2b1a-a1c7-4776-8a74-ff56e663c3b7", "0.1", "43c4785e-51a8-4805-b17b-b483ab69d83b"]}, tags: []}}}, %Electric.Satellite.SatTransOp{op: {:update, %Electric.Satellite.SatOpUpdate{relation_id: 0, row_data: %Electric.Satellite.SatOpRow{nulls_bitmask: "p", values: ["17cf2b1a-a1c7-4776-8a74-ff56e663c3b7", "", "", ""]}, old_row_data: nil, tags: []}}}, %Electric.Satellite.SatTransOp{op: {:insert, %Electric.Satellite.SatOpInsert{relation_id: 3, row_data: %Electric.Satellite.SatOpRow{nulls_bitmask: <<0>>, values: ["958e2cce-adc0-43a6-8713-ed9f44f940db", "17cf2b1a-a1c7-4776-8a74-ff56e663c3b7", "1.1", "43c4785e-51a8-4805-b17b-b483ab69d83b"]}, tags: []}}}, %Electric.Satellite.SatTransOp{op: {:update, %Electric.Satellite.SatOpUpdate{relation_id: 0, row_data: %Electric.Satellite.SatOpRow{nulls_bitmask: "p", values: ["17cf2b1a-a1c7-4776-8a74-ff56e663c3b7", "", "", ""]}, old_row_data: nil, tags: []}}}, %Electric.Satellite.SatTransOp{op: {:insert, %Electric.Satellite.SatOpInsert{relation_id: 3, row_data: %Electric.Satellite.SatOpRow{nulls_bitmask: <<0>>, values: ["8d1d586a-c49e-4ffd-81c3-c50c48aa83f1", "17cf2b1a-a1c7-4776-8a74-ff56e663c3b7", "2.1", "43c4785e-51a8-4805-b17b-b483ab69d83b"]}, tags: []}}}, %Electric.Satellite.SatTransOp{op: {:update, %Electric.Satellite.SatOpUpdate{relation_id: 3, row_data: %Electric.Satellite.SatOpRow{nulls_bitmask: "p", values: ["59e4b3e6-f932-426e-8157-49607fef93d2", "", "", ""]}, old_row_data: nil, tags: []}}}, %Electric.Satellite.SatTransOp{op: {:update, %Electric.Satellite.SatOpUpdate{relation_id: 1, row_data: %Electric.Satellite.SatOpRow{nulls_bitmask: <<127, 192>>, values: ["ffef2a0c-3e70-4ec9-8970-f4765aedaa7a", "", "", "", "", "", "", "", "", ""]}, old_row_data: nil, tags: []}}}, %Electric.Satellite.SatTransOp{op: {:insert, %Electric.Satellite.SatOpInsert{relation_id: 4, row_data: %Electric.Satellite.SatOpRow{nulls_bitmask: <<16>>, values: ["dc848a30-e2ec-457a-8d8a-4e6ffb69143a", "ffef2a0c-3e70-4ec9-8970-f4765aedaa7a", "59e4b3e6-f932-426e-8157-49607fef93d2", "", "\"A\"", "0", "1696029114691.1", "43c4785e-51a8-4805-b17b-b483ab69d83b"]}, tags: []}}}, %Electric.Satellite.SatTransOp{op: {:update, %Electric.Satellite.SatOpUpdate{relation_id: 3, row_data: %Electric.Satellite.SatOpRow{nulls_bitmask: "p", values: ["958e2cce-adc0-43a6-8713-ed9f44f940db", "", "", ""]}, old_row_data: nil, tags: []}}}, %Electric.Satellite.SatTransOp{op: {:update, %Electric.Satellite.SatOpUpdate{relation_id: 1, row_data: %Electric.Satellite.SatOpRow{nulls_bitmask: <<127, 192>>, values: ["ffef2a0c-3e70-4ec9-8970-f4765aedaa7a", "", "", "", "", "", "", "", "", ""]}, old_row_data: nil, tags: []}}}, %Electric.Satellite.SatTransOp{op: {:insert, %Electric.Satellite.SatOpInsert{relation_id: 4, row_data: %Electric.Satellite.SatOpRow{nulls_bitmask: <<16>>, values: ["a9bdbee7-39fc-4f87-81fc-7cd179150c02", "ffef2a0c-3e70-4ec9-8970-f4765aedaa7a", "958e2cce-adc0-43a6-8713-ed9f44f940db", "", "\"A\"", "0", "1696029114691.1", "43c4785e-51a8-4805-b17b-b483ab69d83b"]}, tags: []}}}, %Electric.Satellite.SatTransOp{op: {:update, %Electric.Satellite.SatOpUpdate{relation_id: 3, row_data: %Electric.Satellite.SatOpRow{nulls_bitmask: "p", values: ["8d1d586a-c49e-4ffd-81c3-c50c48aa83f1", "", "", ""]}, old_row_data: nil, tags: []}}}, %Electric.Satellite.SatTransOp{op: {:update, %Electric.Satellite.SatOpUpdate{relation_id: 1, row_data: %Electric.Satellite.SatOpRow{nulls_bitmask: <<127, 192>>, values: ["ffef2a0c-3e70-4ec9-8970-f4765aedaa7a", "", "", "", "", "", "", "", "", ""]}, old_row_data: nil, tags: []}}}, %Electric.Satellite.SatTransOp{op: {:insert, %Electric.Satellite.SatOpInsert{relation_id: 4, row_data: %Electric.Satellite.SatOpRow{nulls_bitmask: <<16>>, values: ["cb04f540-c40a-4599-87dd-55740aca9cb1", "ffef2a0c-3e70-4ec9-8970-f4765aedaa7a", "8d1d586a-c49e-4ffd-81c3-c50c48aa83f1", "", "\"A\"", "0", "1696029114691.1", "43c4785e-51a8-4805-b17b-b483ab69d83b"]}, tags: []}}}, %Electric.Satellite.SatTransOp{op: {:update, %Electric.Satellite.SatOpUpdate{relation_id: 3, row_data: %Electric.Satellite.SatOpRow{nulls_bitmask: "p", values: ["59e4b3e6-f932-426e-8157-49607fef93d2", "", "", ""]}, old_row_data: nil, tags: []}}}, %Electric.Satellite.SatTransOp{op: {:update, %Electric.Satellite.SatOpUpdate{relation_id: 1, row_data: %Electric.Satellite.SatOpRow{nulls_bitmask: <<127, 192>>, values: ["2615e55d-21bc-4f2c-8520-55258d123c85", "", "", "", "", "", "", "", "", ""]}, old_row_data: nil, tags: []}}}, %Electric.Satellite.SatTransOp{op: {:insert, %Electric.Satellite.SatOpInsert{relation_id: 4, row_data: %Electric.Satellite.SatOpRow{nulls_bitmask: <<16>>, values: ["1e652130-012f-49bd-955e-984410644ddd", "2615e55d-21bc-4f2c-8520-55258d123c85", "59e4b3e6-f932-426e-8157-49607fef93d2", "", "\"A\"", "0", "1696029114691.1", "43c4785e-51a8-4805-b17b-b483ab69d83b"]}, tags: []}}}, %Electric.Satellite.SatTransOp{op: {:update, %Electric.Satellite.SatOpUpdate{relation_id: 3, row_data: %Electric.Satellite.SatOpRow{nulls_bitmask: "p", values: ["958e2cce-adc0-43a6-8713-ed9f44f940db", "", "", ""]}, old_row_data: nil, tags: []}}}, %Electric.Satellite.SatTransOp{op: {:update, %Electric.Satellite.SatOpUpdate{relation_id: 1, row_data: %Electric.Satellite.SatOpRow{nulls_bitmask: <<127, 192>>, values: ["2615e55d-21bc-4f2c-8520-55258d123c85", "", "", "", "", "", "", "", "", ""]}, old_row_data: nil, tags: []}}}, %Electric.Satellite.SatTransOp{op: {:insert, %Electric.Satellite.SatOpInsert{relation_id: 4, row_d (truncated)
23:11:55.195 pid=<0.2829.0> client_id=32d8b3f7-8d6f-4d0d-a4e6-baa3b7520447 instance_id=0cac0837-170a-4e79-9ca4-be2c47ca9670 user_id=43c4785e-51a8-4805-b17b-b483ab69d83b [error] ** (MatchError) no match of right hand side value: false
    (electric 0.6.3) lib/electric/satellite/serialization.ex:468: Electric.Satellite.Serialization.decode_column_value!/2
    (electric 0.6.3) lib/electric/satellite/serialization.ex:447: Electric.Satellite.Serialization.decode_values/4
    (electric 0.6.3) lib/electric/satellite/serialization.ex:458: Electric.Satellite.Serialization.decode_values/4
    (electric 0.6.3) lib/electric/satellite/serialization.ex:448: Electric.Satellite.Serialization.decode_values/4
    (electric 0.6.3) lib/electric/satellite/serialization.ex:438: Electric.Satellite.Serialization.decode_record!/3
    (electric 0.6.3) lib/electric/satellite/serialization.ex:391: Electric.Satellite.Serialization.op_to_change/2
    (electric 0.6.3) lib/electric/satellite/serialization.ex:383: anonymous fn/5 in Electric.Satellite.Serialization.deserialize_op_log/5
    (elixir 1.15.4) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
```

**Comment by alco** [comment]
Thanks! We're aware of the issue and are tracking it internally. See also https://github.com/electric-sql/electric/issues/507.

**Comment by alco** [comment]
This has been fixed in version 0.7.0.
