### ISSUE TITLE
can't have healthcheck when ssl is activate

### ISSUE THREAD

**Issue by ulricden** [electric-sql/electric#543]
i try to start a electric-sql server on AWS connect to an RDS Postgresql 15.3

when i try to launch the the service without ssl i have error : 
 ```
 [error] initialization for postgresql failed with reason: {:error, :invalid_authorization_specification}"
 [info] connect: %{database: ~c""database_web"", host: ~c""rds.web.com"", port: 5432, ssl: false, timeout: 5000, username: ~c""username""}"
 [debug] Attempting to initialize postgres_1: username@rds.web.com:5432"
 [info] Running Electric.Plug.Router with Bandit 1.0.0-pre.14 at 0.0.0.0:5133 (http)"
 [notice] :alarm_handler: {:set, {:system_memory_high_watermark, []}}"
```

so i add DATABASE_REQUIRE_SSL = TRUE the i had a new error :

```
"(electric 0.6.4) lib/electric/replication/postgres_manager.ex:92: Electric.Replication.PostgresConnectorMng.handle_continue/2"
"** (MatchError) no match of right hand side value: {:error, {{:shutdown, {:failed_to_start_child, :postgres_producer, {:bad_return_value, {:error, {:error, :error, ""55006"", :object_in_use, ""replication slot \""electric_replication_out_database_web\"" is active for PID 32436"", [file: ""slot.c"", line: ""518"", routine: ""ReplicationSlotAcquire"", severity: ""ERROR""]}}}}}, {:child, :undefined, :sup, {Electric.Replication.PostgresConnectorSup, :start_link, [[origin: ""postgres_1"", producer: Electric.Replication.Postgres.LogicalReplicationProducer, connection: [replication: ""database"", ssl: true, host: ""rds.web.com"", database: ""database_web"", port: 5432, username: ""username"", password: ""*****"", timeout: 5000], replication: [electric_connection: [host: ""electric-tcp.web.com"", port: 5433, dbname: ""electric"", connect_timeout: 5000]]]]}, :temporary, false, :infinity, :supervisor, [Electric.Replication.PostgresConnectorSup]}}}"
"11:39:21.217 pid=<0.2811.0> origin=postgres_1 [error] GenServer #PID<0.2811.0> terminating"
"11:39:21.217 pid=<0.2822.0> [debug] Terminating idle db connection #PID<0.2825.0>"
"11:39:21.216 pid=<0.2824.0> [debug] Elixir.Electric.Replication.Postgres.Client start_replication: slot: 'electric_replication_out_database_web', publication: 'electric_publication'"
"11:39:21.212 pid=<0.2821.0> pg_producer=postgres_1 [info] CREATE TABLE acknowledged_client_lsns (...)"
"11:39:21.210 pid=<0.2824.0> [debug] Elixir.Electric.Replication.Postgres.Client: CREATE_REPLICATION_SLOT ""electric_replication_out_database_web"" LOGICAL pgoutput NOEXPORT_SNAPSHOT"
"Reason: ~c""The option {verify, verify_peer} and one of the options 'cacertfile' or 'cacerts' are required to enable this."""
"11:39:21.198 pid=<0.2826.0> [warning] Description: ~c""Server authenticity is not verified since certificate path validation is not enabled"""
"Reason: ~c""The option {verify, verify_peer} and one of the options 'cacertfile' or 'cacerts' are required to enable this."""
"11:39:21.197 pid=<0.2825.0> [warning] Description: ~c""Server authenticity is not verified since certificate path validation is not enabled"""
"11:39:21.194 pid=<0.2824.0> [debug] Elixir.Electric.Replication.Postgres.LogicalReplicationProducer init:: publication: 'electric_publication', slot: 'electric_replication_out_database_web'"
"11:39:21.194 pid=<0.2822.0> [debug] Starting SchemaLoader pg connection: [origin: ""postgres_1"", producer: Electric.Replication.Postgres.LogicalReplicationProducer, connection: [replication: ""database"", ssl: true, host: ""rds.web.com"", database: ""database_web"", port: 5432, username: ""username"", password: ""*****"", timeout: 5000], replication: [electric_connection: [host: ""electric-tcp.web.com"", port: 5433, dbname: ""electric"", connect_timeout: 5000]]]"
"11:39:21.194 pid=<0.2821.0> pg_producer=postgres_1 [warning] SchemaCache ""postgres_1"" registered as the global instance"
"11:39:21.194 pid=<0.2821.0> pg_producer=postgres_1 [info] Starting Elixir.Electric.Postgres.Extension.SchemaCache for postgres_1"
"11:39:21.194 pid=<0.2811.0> origin=postgres_1 [info] Successfully initialized origin postgres_1 at extension version"
"ORDER BY oid"
"WHERE typtype != 'c'"
"JOIN pg_namespace ON typnamespace = pg_namespace.oid"
"FROM pg_type"
"11:39:21.190 pid=<0.2811.0> origin=postgres_1 [debug] Elixir.Electric.Replication.Postgres.Client: SELECT nspname, typname, pg_type.oid, typarray, typelem, typlen, typtype, typbasetype, typrelid, EXISTS(SELECT 1 FROM pg_type as t WHERE pg_type.oid = t.typarray) as is_array"
"11:39:21.189 pid=<0.2811.0> origin=postgres_1 [debug] Elixir.Electric.Replication.Postgres.Client: CREATE SUBSCRIPTION ""postgres_1"" CONNECTION 'host=electric-tcp.web.com port=5433 dbname=electric connect_timeout=5000' PUBLICATION ""electric_publication"" WITH (connect = false)"
"Reason: ~c""The option {verify, verify_peer} and one of the options 'cacertfile' or 'cacerts' are required to enable this."""
"11:39:21.168 pid=<0.2813.0> [warning] Description: ~c""Server authenticity is not verified since certificate path validation is not enabled"""
"11:39:21.161 pid=<0.2811.0> origin=postgres_1 [info] connect: %{database: ~c""database_web"", host: ~c""rds.web.com"", port: 5432, ssl: true, timeout: 5000, username: ~c""username""}"
"11:39:21.161 pid=<0.2811.0> origin=postgres_1 [debug] Attempting to initialize postgres_1: username@rds.web.com:5432"
"11:39:21.161 pid=<0.2195.0> [info] Running Electric.Plug.Router with Bandit 1.0.0-pre.14 at 0.0.0.0:5133 (http)"
```

if i try to check th health check ai have a new error :

```
"Last message: {:continue, :handle_connection}"
"(electric 0.6.4) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in Electric.Plug.Router.dispatch/2"
"(plug 1.14.2) lib/plug.ex:168: Plug.forward/4"
"(electric 0.6.4) lib/electric/plug/status.ex:1: Electric.Plug.Status.plug_builder_call/2"
"(electric 0.6.4) deps/plug/lib/plug/router.ex:242: Electric.Plug.Status.dispatch/2"
"(telemetry 1.2.1) /app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3"
"(electric 0.6.4) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in Electric.Plug.Status.dispatch/2"
"(electric 0.6.4) lib/electric/plug/status.ex:15: anonymous fn/2 in Electric.Plug.Status.do_match/4"
"(elixir 1.15.4) lib/gen_server.ex:1074: GenServer.call/3"
"** (EXIT) time out"
"** (stop) exited in: GenServer.call({:via, :gproc, {:n, :l, {Electric.Replication.PostgresConnectorMng, ""postgres_1""}}}, :status, 5000)"
"16:20:31.009 pid=<0.2845.0> [error] GenServer #PID<0.2845.0> terminating"
"16:20:26.008 pid=<0.2845.0> [info] GET /api/status"
```

![image](https://github.com/ZeroGachis/electric-service/assets/82812998/627aac30-cad5-404d-a3e4-0350e0ad8d0b)

run.sh file
```
DATABASE_URL=postgresql://${RDS_USERNAME}:${RDS_PASSWORD}@${RDS_HOSTNAME_ELEC}:${RDS_PORT}/${RDS_DB_NAME} /app/bin/entrypoint start
```

task definition
```json
{
    "taskDefinitionArn": "arn:aws:ecs:eu-west-1:xxxx:task-definition/electric-service-develop:31",
    "containerDefinitions": [
        {
            "name": "electric",
            "image": "xxxx.dkr.ecr.eu-west-1.amazonaws.com/develop/electric:10-10-2023_13-16-31",
            "cpu": 0,
            "memoryReservation": 50,
            "portMappings": [
                {
                    "containerPort": 5133,
                    "hostPort": 0,
                    "protocol": "tcp"
                },
                {
                    "containerPort": 5433,
                    "hostPort": 0,
                    "protocol": "tcp"
                }
            ],
            "essential": true,
            "entryPoint": [
                "/bin/bash",
                "/home/src/electric-service/scripts/run.sh"
            ],
            "command": [
                "scripts/run.sh"
            ],
            "environment": [
                {
                    "name": "LOGICAL_PUBLISHER_HOST",
                    "value": "electric-tcp.web.com"
                },
                {
                    "name": "ENV_TYPE",
                    "value": "stage"
                }
            ],
            "mountPoints": [],
            "volumesFrom": [],
            "workingDirectory": "/home/src/electric-service",
            "dockerLabels": {
                "traefik.enable": "true",
                "traefik.http.routers.electric.rule": "Host(`electric.stage.web.com`)",
                "traefik.http.routers.electric.service": "electric",
                "traefik.http.services.electric.loadbalancer.server.port": "5133"
            }
        }
    ],
    "family": "electric-service-develop",
    "taskRoleArn": "arn:aws:iam::xxx:role/electric-role",
    "revision": 31,
    "volumes": [],
    "status": "ACTIVE",
    "requiresAttributes": [
        {
            "name": "com.amazonaws.ecs.capability.ecr-auth"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.17"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.21"
        },
        {
            "name": "com.amazonaws.ecs.capability.task-iam-role"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"
        }
    ],
    "placementConstraints": [],
    "compatibilities": [
        "EXTERNAL",
        "EC2"
    ],
    "registeredAt": "2023-10-10T13:18:43.050Z"
}
```

**Comment by thruflo** [comment]
Thanks for posting the logs and the config. We'll take a look and come back to you.

**Comment by ulricden** [comment]
I try to go through pgbouncer but it doesn't work

`{:error, {{:shutdown, {:failed_to_start_child, :postgres_producer, {:bad_return_value, {:error, {:error, :fatal, "08P01", :protocol_violation, "unsupported startup parameter: replication", []}}}}}`

**Comment by thruflo** [comment]
You could try https://www.pgpool.net/docs/latest/en/html/configuring-pgpool.html

**Comment by ulricden** [comment]
i can't add more middleware in the stack

**Comment by ulricden** [comment]
have you had time to test the config, I am still searching on my side but my knowledge of elixir is a little limited

**Comment by alco** [comment]
Hey @ulricden. I've experimented with running Electric in AWS ECS using Fargate tasks that connect to an RDS for PostgreSQL instance. Here are some notes to help you address the issues you encountered:
* When you see `{:error, :invalid_authorization_specification}` in the logs, it indicates that PostgreSQL requires incoming connections to be SSL-encrypted. So using `DATABASE_REQUIRE_SSL=true` is a must with RDS.
* The error `{:error, :error, ""55006"", :object_in_use, ""replication slot \""electric_replication_out_database_web\"" is active for PID 32436""` hints at the fact that a different instance of Electric is already trying to start a subscription in Postgres. You must have a single instance of Electric connected to Postgres at any point. Make sure your ECS service is configured to run a single task only and to stop the current task before deploying an updated version of the task definition.
* I haven't figured a proper healthcheck configuration for Electric in ECS yet. I would suggest disabling healthchecks in your task definition for now in order to avoid adding another source of errors.
* Finally, you should have Electric connect to Postgres directly using a superuser role. It will likely not work if you have a pool like pgbouncer in the middle.

Because Electric creates a subscription, a publication, and a slot in the Postgres instance, when you change Electric's configuration you may need to remove those resources manually before the new config is picked up. See instructions at the end of this https://github.com/electric-sql/electric/issues/569#issuecomment-1779339695.

**Comment by alco** [comment]
I'm closing this as an old issue that hasn't seen any activity.

Since this was reported, Electric has significantly progressed in its support for different hosting platforms and ease of configuration. It now includes [the `direct_writes` mode](https://electric-sql.com/blog/2023/12/13/electricsql-v0.8-released#from-superuser-to-supabase) which allows for sidestepping all subscription issues altogether. The latest [v0.9 release](https://electric-sql.com/blog/2024/01/24/electricsql-v0.9-released#configuration-improvements-for-easier-deployments) introduces improvements to the use of SSL with database connections and better error reporting in case something goes wrong still.
