### ISSUE TITLE
client:generate error P1017

### ISSUE THREAD

**Issue by barbalex** [electric-sql/electric#714]
After trying to electrify a table and first not succeeding due to seemingly not supported default values (though that seems not to be documented) I now finally managed to electrify my first table.

Unfortunately, since, when I run `npm run client:generate` I get this error:
```console
alex@pop-os:~/ps$ npm run client:generate

> ps@0.1.0 client:generate
> npm run electric:check && npx electric-sql generate --service http://localhost:5133 --proxy postgresql://prisma:proxy_password@localhost:65432/electric


> ps@0.1.0 electric:check
> node ./check-electric-is-running.js

DATABASE_URL: postgresql://postgres:proxy_password@localhost:65432/ps
Error: Command failed: npx prisma db pull --schema=".electric_migrations_tmp_vCB29R/prisma/schema.prisma"
Error: P1017

Server has closed the connection.


    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:526:35)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'npx prisma db pull --schema=".electric_migrations_tmp_vCB29R/prisma/schema.prisma"'
}
generate command failed: Introspection script exited with error code: 1
```

The original table had been:
```sql
CREATE TABLE users(
  user_id uuid PRIMARY KEY DEFAULT public.uuid_generate_v7(),
  email text DEFAULT NULL,
  auth_id uuid DEFAULT NULL,
  deleted boolean DEFAULT FALSE
);
```

The one I managed to electrify is:
```sql
CREATE TABLE users(
  user_id uuid PRIMARY KEY DEFAULT NULL,
  email text DEFAULT NULL, 
  auth_id uuid DEFAULT NULL,
  deleted boolean DEFAULT NULL
);

CREATE INDEX ON users USING btree(user_id);

CREATE INDEX ON users USING btree(email);

CREATE INDEX ON users((1))
WHERE
  deleted;

COMMENT ON COLUMN users.email IS 'email needs to be unique. project manager can list project user by email before this user creates an own login (thus has no user_id yet)';

COMMENT ON TABLE users IS 'Goal: manage users and authorize them';
```

The only thing I can imagine being slightly unusual is the index on deleted.

**Comment by thruflo** [comment]
Do you see anything in the electric logs?

**Comment by barbalex** [comment]
Here is an extract from ps-electric-1 in docker:
```
2023-12-01 14:08:58 13:08:58.607 pid=<0.3435.0> proxy_session_id=8 [warning] Not validating user "prisma"
2023-12-01 14:08:58 13:08:58.607 pid=<0.3435.0> proxy_session_id=8 [info] Initialising injector in capture mode %Electric.Postgres.Proxy.Injector.Prisma{config: %Electric.Postgres.Proxy.Prisma{server_version: {"14.9", 140009}}, prepared_statements: %{}, active_statement: nil, portals: %{}}
2023-12-01 14:08:58 13:08:58.609 pid=<0.3435.0> proxy_session_id=8 [info] Upstream connection is ready to accept queries
2023-12-01 14:08:58 13:08:58.611 pid=<0.3435.0> proxy_session_id=8 [info] Matched prisma introspection query to Elixir.Electric.Postgres.Proxy.Prisma.Query.NamespaceVersionV5_2
2023-12-01 14:08:58 13:08:58.611 pid=<0.3435.0> proxy_session_id=8 [info] Matched prisma introspection query to Elixir.Electric.Postgres.Proxy.Prisma.Query.NamespaceV5_2
2023-12-01 14:08:58 13:08:58.612 pid=<0.3435.0> proxy_session_id=8 [info] Matched prisma introspection query to Elixir.Electric.Postgres.Proxy.Prisma.Query.TableV5_2
2023-12-01 14:08:58 13:08:58.613 pid=<0.3435.0> proxy_session_id=8 [info] Matched prisma introspection query to Elixir.Electric.Postgres.Proxy.Prisma.Query.ConstraintV5_2
2023-12-01 14:08:58 13:08:58.613 pid=<0.3435.0> proxy_session_id=8 [info] Matched prisma introspection query to Elixir.Electric.Postgres.Proxy.Prisma.Query.ViewV5_2
2023-12-01 14:08:58 13:08:58.614 pid=<0.3435.0> proxy_session_id=8 [info] Matched prisma introspection query to Elixir.Electric.Postgres.Proxy.Prisma.Query.TypeV5_2
2023-12-01 14:08:58 13:08:58.614 pid=<0.3435.0> proxy_session_id=8 [info] Matched prisma introspection query to Elixir.Electric.Postgres.Proxy.Prisma.Query.ColumnV5_2
2023-12-01 14:08:58 13:08:58.615 pid=<0.3435.0> proxy_session_id=8 [info] Matched prisma introspection query to Elixir.Electric.Postgres.Proxy.Prisma.Query.ForeignKeyV5_2
2023-12-01 14:08:58 13:08:58.616 pid=<0.3435.0> proxy_session_id=8 [info] Matched prisma introspection query to Elixir.Electric.Postgres.Proxy.Prisma.Query.IndexV5_2
2023-12-01 14:08:58 13:08:58.616 pid=<0.3435.0> proxy_session_id=8 [error] GenServer #PID<0.3435.0> terminating
2023-12-01 14:08:58 ** (RuntimeError) column  not found in table "public"."users"
2023-12-01 14:08:58     (electric 0.7.1) lib/electric/postgres/proxy/prisma/query.ex:1663: Electric.Postgres.Proxy.Prisma.Query.IndexV5_2.column_def/2
2023-12-01 14:08:58     (electric 0.7.1) lib/electric/postgres/proxy/prisma/query.ex:1608: anonymous fn/3 in Electric.Postgres.Proxy.Prisma.Query.IndexV5_2.table_indexes/2
2023-12-01 14:08:58     (elixir 1.15.4) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
2023-12-01 14:08:58     (elixir 1.15.4) lib/enum.ex:4317: Enum.flat_map_list/2
2023-12-01 14:08:58     (elixir 1.15.4) lib/enum.ex:4318: Enum.flat_map_list/2
2023-12-01 14:08:58     (electric 0.7.1) lib/electric/postgres/proxy/prisma/query.ex:1604: Electric.Postgres.Proxy.Prisma.Query.IndexV5_2.table_indexes/2
2023-12-01 14:08:58     (elixir 1.15.4) lib/enum.ex:4317: Enum.flat_map_list/2
2023-12-01 14:08:58     (elixir 1.15.4) lib/enum.ex:4318: Enum.flat_map_list/2
2023-12-01 14:08:58 Last message: {:tcp, #Port<0.40>, <<66, 0, 0, 0, 52, 0, 115, 57, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 30, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 19, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 6, 112, 117, 98, 108, ...>>}
```

**Comment by thruflo** [comment]
Yes, looks like it's documented here: https://www.prisma.io/docs/guides/migrate/developing-with-prisma-migrate/include-unsupported-database-features
