### ISSUE TITLE
Suggestion: better error message when electrifying table with missing primary key

### ISSUE THREAD

**Issue by barbalex** [electric-sql/electric#717]
I was electrifying this table:
```sql
CREATE TABLE widgets_for_fields(
  field_type text DEFAULT NULL REFERENCES field_types(field_type) ON DELETE CASCADE ON UPDATE CASCADE,
  widget_type text DEFAULT NULL REFERENCES widget_types(widget_type) ON DELETE CASCADE ON UPDATE CASCADE,
  deleted boolean DEFAULT NULL -- FALSE
);
```

and got this error:
```console
alexandergabriel@MacBook-Air ps % npm run db:migrate

> ps@0.1.0 db:migrate
> node ./db/migrate.js

DATABASE_URL: postgresql://postgres:proxy_password@localhost:65432/ps
Connecting to proxy at postgresql://postgres@localhost:65432/ps
warning package.json: No license field                                                                                                                                      
Applying 38-widgets_for_fields.sql
error: syntax error at or near ")"
    at handleError (/Users/alexandergabriel/ps/node_modules/@databases/pg/lib/Driver.js:397:29)
    at executeQueryInternal (/Users/alexandergabriel/ps/node_modules/@databases/pg/lib/Driver.js:369:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PgDriver._executeQuery (/Users/alexandergabriel/ps/node_modules/@databases/pg/lib/Driver.js:199:29)
    at async PgDriver.executeAndReturnLast (/Users/alexandergabriel/ps/node_modules/@databases/pg/lib/Driver.js:226:16)
    at async Transaction.query (/Users/alexandergabriel/ps/node_modules/@databases/shared/lib/BaseTransaction.js:59:24)
    at async /Users/alexandergabriel/ps/node_modules/@databases/pg-migrations/lib/PostgresDatabaseEngine.js:19:25
    at async Object.applyMigration (/Users/alexandergabriel/ps/node_modules/@databases/pg-migrations/lib/PostgresDatabaseEngine.js:137:21)
    at async /Users/alexandergabriel/ps/node_modules/@databases/migrations-base/lib/methods/applyOperations.js:43:29
    at async /Users/alexandergabriel/ps/node_modules/@databases/pg-migrations/lib/PostgresDatabaseEngine.js:54:20
 Failed to connect to the DB. Exit code: 1 
```

I then noticed that electric-sql is not happy with the fact that this table has an (undeclared) primary key over the two foreign key fields i.e. is missing a single declared primary key. 

This here works:
```sql
CREATE TABLE widgets_for_fields(
  widgets_for_field_id uuid PRIMARY KEY DEFAULT NULL,
  field_type text DEFAULT NULL REFERENCES field_types(field_type) ON DELETE CASCADE ON UPDATE CASCADE,
  widget_type text DEFAULT NULL REFERENCES widget_types(widget_type) ON DELETE CASCADE ON UPDATE CASCADE,
  deleted boolean DEFAULT NULL -- FALSE
);
```

My suggestion: Please respond with a more descriptive error message than `error: syntax error at or near ")"`.

**Comment by thruflo** [comment]
Thanks for the report. Tweaked docs: https://github.com/electric-sql/electric/pull/722
