### ISSUE TITLE
Cannot read properties of undefined (reading 'numTables') thrown during electrification of Capacitor adapter

### ISSUE THREAD

**Issue by ccapndave** [electric-sql/electric#756]
After updating to Electric 0.8, we get this error during the call to `electrify` (using the Capacitor plugin):

```
process.js:7 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'numTables')
    at he._verifyTableStructure (process.js:7:19)
    at async he.start (process.js:1:2393)
    at async b7.startProcess (registry.js:1:1777)
    at async T6 (index.js:1:611)
    at async h5 (index.js:1:245)
    at async makeElectric (database.ts:80:10)
    at async initDatabases (database.ts:94:20)
    at async init (main.tsx:24:15)
_verifyTableStructure @ process.js:7
```

**Comment by gregzo** [comment]
I see the problem.

I've misunderstood the documentation for Capcitor SQLite's `run` method:
<!DOCTYPE html>
values | any[] | values when RETURNING
-- | -- | --

The `exec()` method should instead map to Cap-SQLite's `query()` method.

I'll make a PR shortly.

**Comment by kevin-dp** [comment]
I'm closing this as we've merged https://github.com/electric-sql/electric/pull/760 which addresses this issue.
