### ISSUE TITLE
Error when running an update query — Internal UPDATE has an extra comma

### ISSUE THREAD

**Issue by KyleAMathews** [electric-sql/electric#801]
```
error: syntax error at or near "WHERE"
    at /Users/kylemathews/programs/life-logger/node_modules/pg/lib/client.js:526:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at (/Users/kylemathews/programs/life-logger/src/backend/garmin.ts:95:9)
    at async Promise.all (index 0)
    at main (/Users/kylemathews/programs/life-logger/src/backend/garmin.ts:40:5) {
  length: 338,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: '148',
  internalQuery: 'UPDATE electric.shadow__public__events\n' +
    ' SET _tag = $2, _tags = ARRAY[$2], _resolved = true, _modified_columns_bit_mask = array[]::boolean[], \n' +
    ' WHERE id = $1',
  where: 'PL/pgSQL function electric.write_correct_max_tag___public__events() line 33 at EXECUTE',
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1176',
  routine: 'scanner_yyerror'
}
```

The query looks like:

```
{
  query: '\n' +
    ' INSERT INTO events (id, type, created_at, user_id, attributes)\n' +
    ' VALUES ($1, $2, $3, $4, $5)\n' +
    ' ',
  values: [
    '992348d3-cc9a-4a51-9873-14c18d3d7e61',
    '617aee13-af15-49a0-b855-5cc781abd5d9',
    2023-12-27T01:39:59.000Z,
    'user_2ZrWJQijcAkujdv4nQMOYaE1Obi',
    '{"activityId":13242153626,"activityName":"Indoor Cycling","activityType":{"typeKey":"indoor_cycling"},"startTimeGMT":"202
3-12-27 01:39:59","distance":11265.408000000001,"elapsedDuration":1805.56298828125,"averageHR":107,"steps":null,"avgPower":0}'
  ]
}
```

**Comment by icehaunter** [comment]
Hey @KyleAMathews! Thanks for the report. Was this a one-off error or was it reproducible? I found the code path that may lead to this error, but I'm unsure yet how you triggered it. Would you mind connecting to the database with `psql` and running `\sf electric.create_shadow_row_from_upsert___public__events`?

**Comment by KyleAMathews** [comment]
Yeah it happens every time I run an update to postgres against a row with a JSON column where there wasn't actually any changes — if any of the JSON data does change, then the error doesn't happen.
